/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CopperProductType = { 'copperPipe' : null } |
  { 'copperWire' : null } |
  { 'copperSheet' : null } |
  { 'copperRod' : null };
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export type SellerAvailability = { 'available' : null } |
  { 'unavailable' : null } |
  { 'partial' : null };
export interface ProductItem {
  'productType' : CopperProductType,
  'size' : string,
  'quantity' : bigint,
  'unitOfMeasurement' : string,
}
export interface PurchaseOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'items' : Array<ProductItem>,
  'email' : string,
  'timestamp' : bigint,
  'companyName' : string,
  'phoneNumber' : string,
  'requiredDeliveryDate' : string,
  'specialNotes' : string,
  'sellerReply' : [] | [string],
  'sellerAvailability' : [] | [SellerAvailability],
  'sellerReplyTimestamp' : [] | [bigint],
}
export interface PurchaseOrderInput {
  'customerName' : string,
  'items' : Array<ProductItem>,
  'email' : string,
  'companyName' : string,
  'phoneNumber' : string,
  'requiredDeliveryDate' : string,
  'specialNotes' : string,
}
export interface ProductRate {
  'productType' : CopperProductType,
  'pricePerUnit' : string,
  'currency' : string,
  'unit' : string,
  'notes' : string,
  'updatedAt' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPurchaseOrders' : ActorMethod<[], Array<PurchaseOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrderConfirmation' : ActorMethod<[bigint], [] | [PurchaseOrder]>,
  'getOrderSummary' : ActorMethod<
    [],
    {
      'cancelledOrders' : bigint,
      'totalOrders' : bigint,
      'pendingOrders' : bigint,
      'processingOrders' : bigint,
      'completedOrders' : bigint,
      'shippedOrders' : bigint,
      'awaitingReply' : bigint,
    }
  >,
  'getOrdersByCompany' : ActorMethod<[string], Array<PurchaseOrder>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<PurchaseOrder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'replyToOrder' : ActorMethod<[bigint, SellerAvailability, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setProductRate' : ActorMethod<[CopperProductType, string, string, string, string], undefined>,
  'getProductRates' : ActorMethod<[], Array<ProductRate>>,
  'submitPurchaseOrder' : ActorMethod<[PurchaseOrderInput], bigint>,
  'trackOrder' : ActorMethod<[bigint, string], [] | [PurchaseOrder]>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
