/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductItem {
    productType: CopperProductType;
    size: string;
    quantity: bigint;
    unitOfMeasurement: string;
}
export interface PurchaseOrder {
    id: bigint;
    customerName: string;
    status: OrderStatus;
    items: Array<ProductItem>;
    email: string;
    timestamp: bigint;
    companyName: string;
    phoneNumber: string;
    requiredDeliveryDate: string;
    specialNotes: string;
    sellerReply: string | null;
    sellerAvailability: SellerAvailability | null;
    sellerReplyTimestamp: bigint | null;
}
export interface UserProfile {
    name: string;
}
export interface PurchaseOrderInput {
    customerName: string;
    items: Array<ProductItem>;
    email: string;
    companyName: string;
    phoneNumber: string;
    requiredDeliveryDate: string;
    specialNotes: string;
}
export enum CopperProductType {
    copperPipe = "copperPipe",
    copperWire = "copperWire",
    copperSheet = "copperSheet",
    copperRod = "copperRod"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    processing = "processing"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum SellerAvailability {
    available = "available",
    unavailable = "unavailable",
    partial = "partial"
}
export interface ProductRate {
    productType: string;
    pricePerUnit: string;
    currency: string;
    unit: string;
    notes: string;
    updatedAt: bigint;
}


export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllPurchaseOrders(): Promise<Array<PurchaseOrder>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getOrderConfirmation(orderId: bigint): Promise<PurchaseOrder | null>;
    getOrderSummary(): Promise<{
        cancelledOrders: bigint;
        totalOrders: bigint;
        pendingOrders: bigint;
        processingOrders: bigint;
        completedOrders: bigint;
        shippedOrders: bigint;
        awaitingReply: bigint;
    }>;
    getOrdersByCompany(companyName: string): Promise<Array<PurchaseOrder>>;
    getOrdersByStatus(status: OrderStatus): Promise<Array<PurchaseOrder>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitPurchaseOrder(orderInput: PurchaseOrderInput): Promise<bigint>;
    updateOrderStatus(orderId: bigint, newStatus: OrderStatus): Promise<void>;
    replyToOrder(orderId: bigint, availability: SellerAvailability, replyMessage: string): Promise<void>;
    trackOrder(orderId: bigint, email: string): Promise<PurchaseOrder | null>;
    setProductRate(productType: CopperProductType, pricePerUnit: string, currency: string, unit: string, notes: string): Promise<void>;
    getProductRates(): Promise<Array<ProductRate>>;
}
import type { CopperProductType as _CopperProductType, OrderStatus as _OrderStatus, PurchaseOrder as _PurchaseOrder, PurchaseOrderInput as _PurchaseOrderInput, ProductItem as _ProductItem, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole(arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole(arg1));
            return result;
        }
    }
    async getAllPurchaseOrders(): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPurchaseOrders();
                return result.map(from_candid_PurchaseOrder);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPurchaseOrders();
            return result.map(from_candid_PurchaseOrder);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return result.length === 0 ? null : result[0];
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole(result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole(result);
        }
    }
    async getOrderConfirmation(arg0: bigint): Promise<PurchaseOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderConfirmation(arg0);
                return result.length === 0 ? null : from_candid_PurchaseOrder(result[0]);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderConfirmation(arg0);
            return result.length === 0 ? null : from_candid_PurchaseOrder(result[0]);
        }
    }
    async getOrderSummary(): Promise<{
        cancelledOrders: bigint;
        totalOrders: bigint;
        pendingOrders: bigint;
        processingOrders: bigint;
        completedOrders: bigint;
        shippedOrders: bigint;
        awaitingReply: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderSummary();
            return result;
        }
    }
    async getOrdersByCompany(arg0: string): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByCompany(arg0);
                return result.map(from_candid_PurchaseOrder);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByCompany(arg0);
            return result.map(from_candid_PurchaseOrder);
        }
    }
    async getOrdersByStatus(arg0: OrderStatus): Promise<Array<PurchaseOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus(arg0));
                return result.map(from_candid_PurchaseOrder);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_OrderStatus(arg0));
            return result.map(from_candid_PurchaseOrder);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return result.length === 0 ? null : result[0];
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitPurchaseOrder(arg0: PurchaseOrderInput): Promise<bigint> {
        const candid_input = {
            customerName: arg0.customerName,
            items: arg0.items.map(to_candid_ProductItem),
            email: arg0.email,
            companyName: arg0.companyName,
            phoneNumber: arg0.phoneNumber,
            requiredDeliveryDate: arg0.requiredDeliveryDate,
            specialNotes: arg0.specialNotes,
        };
        if (this.processError) {
            try {
                const result = await this.actor.submitPurchaseOrder(candid_input);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPurchaseOrder(candid_input);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus(arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus(arg1));
            return result;
        }
    }
    async replyToOrder(arg0: bigint, arg1: SellerAvailability, arg2: string): Promise<void> {
        const result = await this.actor.replyToOrder(arg0, to_candid_SellerAvailability(arg1), arg2);
        return result;
    }
    async trackOrder(arg0: bigint, arg1: string): Promise<PurchaseOrder | null> {
        const result = await this.actor.trackOrder(arg0, arg1);
        return result.length === 0 ? null : from_candid_PurchaseOrder(result[0]);
    }
    async setProductRate(arg0: CopperProductType, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        const result = await this.actor.setProductRate(to_candid_CopperProductType(arg0), arg1, arg2, arg3, arg4);
        return result;
    }
    async getProductRates(): Promise<Array<ProductRate>> {
        const result = await this.actor.getProductRates();
        return result.map((r) => ({
            productType: from_candid_CopperProductType(r.productType),
            pricePerUnit: r.pricePerUnit,
            currency: r.currency,
            unit: r.unit,
            notes: r.notes,
            updatedAt: r.updatedAt,
        }));
    }
}

function to_candid_ProductItem(item: ProductItem): _ProductItem {
    return {
        productType: to_candid_CopperProductType(item.productType),
        size: item.size,
        quantity: item.quantity,
        unitOfMeasurement: item.unitOfMeasurement,
    };
}

function from_candid_ProductItem(item: _ProductItem): ProductItem {
    return {
        productType: from_candid_CopperProductType(item.productType),
        size: item.size,
        quantity: item.quantity,
        unitOfMeasurement: item.unitOfMeasurement,
    };
}

function from_candid_PurchaseOrder(value: _PurchaseOrder): PurchaseOrder {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus(value.status),
        items: value.items.map(from_candid_ProductItem),
        email: value.email,
        timestamp: value.timestamp,
        companyName: value.companyName,
        phoneNumber: value.phoneNumber,
        requiredDeliveryDate: value.requiredDeliveryDate,
        specialNotes: value.specialNotes,
        sellerReply: value.sellerReply.length === 0 ? null : value.sellerReply[0],
        sellerAvailability: value.sellerAvailability.length === 0 ? null : from_candid_SellerAvailability(value.sellerAvailability[0]),
        sellerReplyTimestamp: value.sellerReplyTimestamp.length === 0 ? null : value.sellerReplyTimestamp[0],
    };
}

function from_candid_CopperProductType(value: _CopperProductType): CopperProductType {
    return "copperPipe" in value ? CopperProductType.copperPipe
        : "copperWire" in value ? CopperProductType.copperWire
        : "copperSheet" in value ? CopperProductType.copperSheet
        : CopperProductType.copperRod;
}

function to_candid_CopperProductType(value: CopperProductType): _CopperProductType {
    return value == CopperProductType.copperPipe ? { copperPipe: null }
        : value == CopperProductType.copperWire ? { copperWire: null }
        : value == CopperProductType.copperSheet ? { copperSheet: null }
        : { copperRod: null };
}

function from_candid_OrderStatus(value: _OrderStatus): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped
        : "cancelled" in value ? OrderStatus.cancelled
        : "pending" in value ? OrderStatus.pending
        : "completed" in value ? OrderStatus.completed
        : OrderStatus.processing;
}

function to_candid_OrderStatus(value: OrderStatus): _OrderStatus {
    return value == OrderStatus.shipped ? { shipped: null }
        : value == OrderStatus.cancelled ? { cancelled: null }
        : value == OrderStatus.pending ? { pending: null }
        : value == OrderStatus.completed ? { completed: null }
        : { processing: null };
}

function from_candid_UserRole(value): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : UserRole.guest;
}

function to_candid_UserRole(value: UserRole): any {
    return value == UserRole.admin ? { admin: null } : value == UserRole.user ? { user: null } : { guest: null };
}

function from_candid_SellerAvailability(value): SellerAvailability {
    return "available" in value ? SellerAvailability.available
        : "unavailable" in value ? SellerAvailability.unavailable
        : SellerAvailability.partial;
}

function to_candid_SellerAvailability(value): any {
    return value == "available" || value == SellerAvailability.available ? { available: null }
        : value == "unavailable" || value == SellerAvailability.unavailable ? { unavailable: null }
        : { partial: null };
}

export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
